# name: Python CI

# on: [push, pull_request]

# jobs:
#   test:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v4

#       - name: Set up Python
#         uses: actions/setup-python@v4
#         with:
#           python-version: 3.11

#       - name: Install dependencies
#         run: |
#           pip install -e '.[dev]'
#           pip install pytest pytest-cov coverage

#       - name: Install HiGHS
#         run: sudo apt install -y coinor-cbc

#       - name: Run pytest
#         run: |
#           pytest
